title: P & P dis mov 02
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

# Configuración del esquema de color
color_scheme: dark

# Agregando el favicon
favicon_ico: "/assets/images/post.ico"

# Set a path/url to a logo that will be displayed instead of the title logo
logo: "/assets/images/uvm.png"

title_only_logo: false

plugins:
  - jekyll-feed

title: Principios y prácticas del diseño en movimiento II
description: Espacio de la materia de ingeniería en animación.
url: "https://beztao01.github.io/principios02/" # O tu dominio local http://127.0.0.1:4000
#aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
